### ISSUE TITLE
Tracking issue for our new EVM implementation

### ISSUE THREAD

**Issue by MOZGIII** [humanode-network/humanode#676]
## Design

- [Preliminary](https://www.notion.so/humanode-network/EVM-discussion-prep-materials-5e088236021c456cb4503902c72a73ba)
- [Current](https://www.notion.so/humanode-network/Implementation-faefc2559a7b41e5862a83552a5ad39b)

### Design phase

- [x] https://github.com/humanode-network/arch/pull/47
- [x] https://github.com/humanode-network/arch/pull/49

### EVM accounts

- [x] https://github.com/humanode-network/frontier/pull/61
- [x] https://github.com/humanode-network/frontier/pull/62
- [x] https://github.com/humanode-network/frontier/pull/63
- [x] https://github.com/humanode-network/frontier/pull/64

### EVM balances

- [x] https://github.com/humanode-network/frontier/pull/65
- [x] https://github.com/humanode-network/frontier/pull/66
- [x] https://github.com/humanode-network/frontier/pull/67
- [x] https://github.com/humanode-network/frontier/pull/68
- [x] https://github.com/humanode-network/frontier/pull/69
- [x] https://github.com/humanode-network/frontier/pull/70
- [x] https://github.com/humanode-network/frontier/pull/71

### Currency swap

- [x] https://github.com/humanode-network/humanode/issues/678
- [x] https://github.com/humanode-network/humanode/pull/680
- [x] https://github.com/humanode-network/humanode/pull/682
- [x] https://github.com/humanode-network/humanode/pull/684
- [x] https://github.com/humanode-network/humanode/pull/686
- [x] https://github.com/humanode-network/humanode/pull/679
- [x] https://github.com/humanode-network/humanode/pull/685
- [x] https://github.com/humanode-network/humanode/pull/673
- [x] #692
- [x] https://github.com/humanode-network/humanode/pull/716
- [x] https://github.com/humanode-network/humanode/pull/719

### Fee adjustments

- [x] #688

### Mainnet rollout

- [x] EVM state migration (nothing to do here, we are lucky)

### Usability improvements

- [x] #696
- [x] Prepare user-facing documentation for the new EVM design (update gitbook)

### Bugfixes

- [x] Do not deduct ED when reading the balance via the RPC
- [x] #781
- [x] #762
- [x] #763

**Comment by MOZGIII** [comment]
@dmitrylavrenov what is the state of this?
