### ISSUE TITLE
Tracking issue to bump substrate related deps to `polkadot-sdk-v1.1.0`

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#807]
### `polkadot-sdk` fork

- [x] Prepare locked branch 
https://github.com/humanode-network/polkadot-sdk/tree/locked/release-polkadot-v1.1.0

### `frontier` fork

- [x] https://github.com/humanode-network/frontier/pull/75
- [x] https://github.com/humanode-network/frontier/pull/76
- [x] https://github.com/humanode-network/frontier/pull/77
- [x] https://github.com/humanode-network/frontier/pull/78

### `humanode-network`

- [ ] https://github.com/humanode-network/humanode/pull/803

**Comment by dmitrylavrenov** [comment]
Switched to do updates step by step
