### ISSUE TITLE
Tracking issue to bump `substrate` related deps to `polkadot-v0.9.39`

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#828]
### `paritytech/substrate`

https://github.com/paritytech/substrate/compare/polkadot-v0.9.38...paritytech:substrate:polkadot-v0.9.39

### `paritytech/frontier`

https://github.com/paritytech/frontier/compare/98aacf69e976340338f81455e48e8b330007e544...paritytech:frontier:aeb85c3fdad53fa5c146ded0bba03bd795ad9e42

### `humanode-network/substrate` fork

- [x] Prepare locked branch 
https://github.com/humanode-network/substrate/tree/locked/polkadot-v0.9.39
- [x] https://github.com/humanode-network/substrate/pull/91
- [x] https://github.com/humanode-network/substrate/pull/92

### `humanode-network/frontier` fork

- [x] https://github.com/humanode-network/frontier/pull/82
- [x] https://github.com/humanode-network/frontier/pull/83
- [x] https://github.com/humanode-network/frontier/pull/84
- [x] https://github.com/humanode-network/frontier/pull/85
- [x] https://github.com/humanode-network/frontier/pull/86
- [x] https://github.com/humanode-network/frontier/pull/87
- [x] https://github.com/humanode-network/frontier/pull/88

### `humanode-network/humanode`

- [x] https://github.com/humanode-network/humanode/pull/829

**Comment by MOZGIII** [comment]
I'll note discussion-worthy stuff here (in no particular order). To be updated.

- https://github.com/paritytech/substrate/pull/13284
