### ISSUE TITLE
Tracking issue to bump `substrate` related deps to `polkadot-v0.9.40`

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#839]
### `paritytech/substrate`

https://github.com/paritytech/substrate/compare/polkadot-v0.9.39...paritytech:substrate:polkadot-v0.9.40

To account for:
- [x] https://github.com/paritytech/substrate/pull/13424
- [x] https://github.com/paritytech/substrate/pull/13372
- [x] https://github.com/paritytech/substrate/pull/13445
- [x] https://github.com/paritytech/substrate/pull/13458
- [x] https://github.com/paritytech/substrate/pull/13468
- [x] https://github.com/paritytech/substrate/pull/13477
- [x] https://github.com/paritytech/substrate/pull/13485
- [x] https://github.com/paritytech/substrate/pull/13484
- [x] https://github.com/paritytech/substrate/pull/13427
- [x] https://github.com/paritytech/substrate/pull/13490
- [x] https://github.com/paritytech/substrate/pull/13486
- [x] https://github.com/paritytech/substrate/pull/13493
- [x] https://github.com/paritytech/substrate/pull/13475
- [x] https://github.com/paritytech/substrate/pull/13378
- [x] https://github.com/paritytech/substrate/pull/12828
- [x] https://github.com/paritytech/substrate/pull/13539
- [x] https://github.com/paritytech/substrate/pull/13379
- [x] https://github.com/paritytech/substrate/pull/13250
- [x] https://github.com/paritytech/substrate/pull/13425
- [x] https://github.com/paritytech/substrate/pull/13559
- [x] https://github.com/paritytech/substrate/pull/13503
- [x] https://github.com/paritytech/substrate/pull/13535
- [x] https://github.com/paritytech/substrate/pull/13452
- [x] https://github.com/paritytech/substrate/pull/13590
- [x] https://github.com/paritytech/substrate/pull/13592
- [x] https://github.com/paritytech/substrate/pull/13573
- [x] https://github.com/paritytech/substrate/pull/13341

### `paritytech/frontier`

https://github.com/paritytech/frontier/compare/aeb85c3fdad53fa5c146ded0bba03bd795ad9e42...paritytech:frontier:3b871456f7a23b17fc01b2d17d895a0bdf60b725

To account for:
- [x] https://github.com/paritytech/frontier/pull/1049
- [x] https://github.com/paritytech/frontier/pull/1058
- [x] https://github.com/paritytech/frontier/pull/893
- [x] https://github.com/paritytech/frontier/pull/1068
- [x] https://github.com/paritytech/frontier/pull/1039
- [x] https://github.com/paritytech/frontier/pull/1079
- [x] https://github.com/paritytech/frontier/pull/1077
- [x] https://github.com/paritytech/frontier/pull/1048
- [x] https://github.com/paritytech/frontier/pull/1073
- [x] https://github.com/paritytech/frontier/pull/1088

### `humanode-network/substrate` fork

- [x] Prepare locked branch 
https://github.com/humanode-network/substrate/tree/locked/polkadot-v0.9.40
- [x] https://github.com/humanode-network/substrate/pull/95
- [x] https://github.com/humanode-network/substrate/pull/96

### `humanode-network/frontier` fork

- [x] Prepare locked branch 
https://github.com/humanode-network/frontier/tree/locked/polkadot-v0.9.40
- [x] https://github.com/humanode-network/frontier/pull/91
- [x] https://github.com/humanode-network/frontier/pull/92
- [x] https://github.com/humanode-network/frontier/pull/93
- [x] https://github.com/humanode-network/frontier/pull/94
- [x] https://github.com/humanode-network/frontier/pull/95

**Comment by MOZGIII** [comment]
WIP

---

To discuss:

- https://github.com/paritytech/substrate/pull/13427

**Comment by MOZGIII** [comment]
This is shipping now, so I'm closing it
