### ISSUE TITLE
Tracking issue to bump `substrate` related deps to `polkadot-v0.9.42`

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#855]
### `paritytech/substrate`

https://github.com/paritytech/substrate/compare/polkadot-v0.9.40...paritytech:substrate:polkadot-v0.9.42

### `paritytech/frontier`

https://github.com/polkadot-evm/frontier/compare/3b871456f7a23b17fc01b2d17d895a0bdf60b725...polkadot-evm:frontier:e89f33688e0e438d0d26ca4f5eaba16a17201a22

### `humanode-network/substrate` fork

- [x] Prepare locked branch 
https://github.com/humanode-network/substrate/tree/locked/polkadot-v0.9.42
- [x] https://github.com/humanode-network/substrate/pull/99
- [x] https://github.com/humanode-network/substrate/pull/100

### `humanode-network/frontier` fork

- [x] Prepare locked branch 
https://github.com/humanode-network/frontier/tree/locked/polkadot-v0.9.42
- [x] https://github.com/humanode-network/frontier/pull/96
- [x] https://github.com/humanode-network/frontier/pull/97
- [x] https://github.com/humanode-network/frontier/pull/98
- [x] https://github.com/humanode-network/frontier/pull/99
- [x] https://github.com/humanode-network/frontier/pull/100
- [x] https://github.com/humanode-network/frontier/pull/102

**Comment by dmitrylavrenov** [comment]
Completed with https://github.com/humanode-network/humanode/pull/861
