### ISSUE TITLE
Tracking issue to bump substrate related deps to `polkadot-v0.9.43`

### ISSUE THREAD

**Issue by dmitrylavrenov** [humanode-network/humanode#923]
### `paritytech/substrate`

https://github.com/paritytech/substrate/compare/polkadot-v0.9.42...paritytech:substrate:polkadot-v0.9.43

### `paritytech/frontier`

https://github.com/polkadot-evm/frontier/compare/e89f33688e0e438d0d26ca4f5eaba16a17201a22...polkadot-evm:frontier:b27304a9e31af245590a1bde892c2bd7a3186b5e

### `humanode-network/substrate` fork

- [x] Prepare a corresponding branch - https://github.com/humanode-network/substrate/commits/h-polkadot-v0.9.43/

### `humanode-network/frontier` fork

- [x] Prepare a corresponding branch 
https://github.com/humanode-network/frontier/commits/h-polkadot-v0.9.43/

**Comment by dmitrylavrenov** [comment]
Interesting commits:

- [ ] https://github.com/paritytech/substrate/pull/13233
- [ ] https://github.com/paritytech/substrate/pull/13999
- [ ] https://github.com/paritytech/substrate/pull/14067
- [ ] https://github.com/paritytech/substrate/pull/13384 (applied - https://github.com/humanode-network/humanode/pull/940/commits/62c5ad6f7e166c15e2bd4c77698236d0e960fd0a)
- [ ] https://github.com/paritytech/substrate/pull/13701 (research more deeply, think if it's useful for us)
- [ ] https://github.com/paritytech/substrate/pull/14036
- [ ] https://github.com/paritytech/substrate/pull/13737
- [ ] https://github.com/paritytech/substrate/pull/13852 (applied at frontier fork - https://github.com/humanode-network/frontier/pull/110)
- [ ] https://github.com/paritytech/substrate/pull/13417
- [ ] https://github.com/paritytech/substrate/pull/14057
- [ ] https://github.com/paritytech/substrate/pull/14083
- [ ] https://github.com/paritytech/substrate/pull/14088
- [ ] https://github.com/paritytech/substrate/pull/13843
- [ ] https://github.com/paritytech/substrate/pull/14094
- [ ] https://github.com/paritytech/substrate/pull/14099
- [ ] https://github.com/paritytech/substrate/pull/13618
- [ ] https://github.com/paritytech/substrate/pull/14080 (applied - https://github.com/humanode-network/humanode/pull/940/commits/772ced80f7051778cc9d4f885d91276ca157e33f)
- [ ] https://github.com/paritytech/substrate/pull/13880 (applied - https://github.com/humanode-network/humanode/pull/940/commits/260f34340116ba0d19ec46c47e973482563d0090)
- [ ] https://github.com/paritytech/substrate/pull/13373 (applied - https://github.com/humanode-network/humanode/pull/940/commits/f756dca6311ac32e9fb7c5443e5ea83ccb7ecea8)
- [ ] https://github.com/paritytech/substrate/pull/13587
- [ ] https://github.com/paritytech/substrate/pull/14149
- [ ] https://github.com/paritytech/substrate/pull/14167
- [ ] https://github.com/paritytech/substrate/pull/14108 (applied - https://github.com/humanode-network/humanode/pull/940/commits/6d5e6b1d97adab908bf54724a23b88139b93ea03)
- [ ] https://github.com/paritytech/substrate/pull/14182
- [ ] https://github.com/paritytech/substrate/pull/14184
- [ ] https://github.com/paritytech/substrate/pull/13993 (applied - https://github.com/humanode-network/humanode/pull/940/commits/f2f1d7aa4d32671db9647437e2426195011045de)
- [ ] https://github.com/paritytech/substrate/pull/14144
- [ ] https://github.com/paritytech/substrate/pull/13611
- [ ] https://github.com/paritytech/substrate/pull/14191
- [ ] https://github.com/paritytech/substrate/pull/14388

**Comment by MOZGIII** [comment]
As a sidenote: I've just discovered this - https://github.com/moonbeam-foundation/moonbeam/blob/master/tools/github/print-version-bump-info.ts

Pretty cool stuff

**Comment by MOZGIII** [comment]
My version of the list from https://github.com/humanode-network/humanode/issues/923#issuecomment-2444025094 so I can keep track.

<details><summary>Details</summary>
<p>


- [ ] https://github.com/paritytech/substrate/pull/13233
- [ ] https://github.com/paritytech/substrate/pull/13999
- [ ] https://github.com/paritytech/substrate/pull/14067
- [ ] https://github.com/paritytech/substrate/pull/13384 (applied - https://github.com/humanode-network/humanode/pull/940/commits/62c5ad6f7e166c15e2bd4c77698236d0e960fd0a)
- [ ] https://github.com/paritytech/substrate/pull/13701 (research more deeply, think if it's useful for us)
- [ ] https://github.com/paritytech/substrate/pull/14036
- [ ] https://github.com/paritytech/substrate/pull/13737
- [ ] https://github.com/paritytech/substrate/pull/13852
- [ ] https://github.com/paritytech/substrate/pull/13417
- [ ] https://github.com/paritytech/substrate/pull/14057
- [ ] https://github.com/paritytech/substrate/pull/14083
- [ ] https://github.com/paritytech/substrate/pull/14088
- [ ] https://github.com/paritytech/substrate/pull/13843
- [ ] https://github.com/paritytech/substrate/pull/14094
- [ ] https://github.com/paritytech/substrate/pull/14099
- [ ] https://github.com/paritytech/substrate/pull/13618
- [ ] https://github.com/paritytech/substrate/pull/14080 (applied - https://github.com/humanode-network/humanode/pull/940/commits/772ced80f7051778cc9d4f885d91276ca157e33f)
- [ ] https://github.com/paritytech/substrate/pull/13880 (applied - https://github.com/humanode-network/humanode/pull/940/commits/260f34340116ba0d19ec46c47e973482563d0090)
- [ ] https://github.com/paritytech/substrate/pull/13373 (applied - https://github.com/humanode-network/humanode/pull/940/commits/f756dca6311ac32e9fb7c5443e5ea83ccb7ecea8)
- [ ] https://github.com/paritytech/substrate/pull/13587
- [ ] https://github.com/paritytech/substrate/pull/14149
- [ ] https://github.com/paritytech/substrate/pull/14167
- [ ] https://github.com/paritytech/substrate/pull/14108 (applied - https://github.com/humanode-network/humanode/pull/940/commits/6d5e6b1d97adab908bf54724a23b88139b93ea03)
- [ ] https://github.com/paritytech/substrate/pull/14182
- [ ] https://github.com/paritytech/substrate/pull/14184
- [ ] https://github.com/paritytech/substrate/pull/13993 (applied - https://github.com/humanode-network/humanode/pull/940/commits/f2f1d7aa4d32671db9647437e2426195011045de)
- [ ] https://github.com/paritytech/substrate/pull/14144
- [ ] https://github.com/paritytech/substrate/pull/13611
- [ ] https://github.com/paritytech/substrate/pull/14191
- [ ] https://github.com/paritytech/substrate/pull/14388

</p>
</details>
